export const stateList = [
	{ value: "AK", key: "AK", text: "Alaska" },
	{ value: "AL", key: "AL", text: "Alabama" },
	{ value: "AR", key: "AR", text: "Arkansas" },
	{ value: "AS", key: "AS", text: "American Samoa" },
	{ value: "AZ", key: "AZ", text: "Arizona" },
	{ value: "CA", key: "CA", text: "California" },
	{ value: "CO", key: "CO", text: "Colorado" },
	{ value: "CT", key: "CT", text: "Connecticut" },
	{ value: "DC", key: "DC", text: "District of Columbia" },
	{ value: "DE", key: "DE", text: "Delaware" },
	{ value: "FL", key: "FL", text: "Florida" },
	{ value: "GA", key: "GA", text: "Georgia" },
	{ value: "GU", key: "GU", text: "Guam" },
	{ value: "HI", key: "HI", text: "Hawaii" },
	{ value: "IA", key: "IA", text: "Iowa" },
	{ value: "ID", key: "ID", text: "Idaho" },
	{ value: "IL", key: "IL", text: "Illinois" },
	{ value: "IN", key: "IN", text: "Indiana" },
	{ value: "KS", key: "KS", text: "Kansas" },
	{ value: "KY", key: "KY", text: "Kentucky" },
	{ value: "LA", key: "LA", text: "Louisiana" },
	{ value: "MA", key: "MA", text: "Massachusetts" },
	{ value: "MD", key: "MD", text: "Maryland" },
	{ value: "ME", key: "ME", text: "Maine" },
	{ value: "MI", key: "MI", text: "Michigan" },
	{ value: "MN", key: "MN", text: "Minnesota" },
	{ value: "MO", key: "MO", text: "Missouri" },
	{ value: "MS", key: "MS", text: "Mississippi" },
	{ value: "MT", key: "MT", text: "Montana" },
	{ value: "NC", key: "NC", text: "North Carolina" },
	{ value: "ND", key: "ND", text: "North Dakota" },
	{ value: "NE", key: "NE", text: "Nebraska" },
	{ value: "NH", key: "NH", text: "New Hampshire" },
	{ value: "NJ", key: "NJ", text: "New Jersey" },
	{ value: "NM", key: "NM", text: "New Mexico" },
	{ value: "NV", key: "NV", text: "Nevada" },
	{ value: "NY", key: "NY", text: "New York" },
	{ value: "OH", key: "OH", text: "Ohio" },
	{ value: "OK", key: "OK", text: "Oklahoma" },
	{ value: "OR", key: "OR", text: "Oregon" },
	{ value: "PA", key: "PA", text: "Pennsylvania" },
	{ value: "PR", key: "PR", text: "Puerto Rico" },
	{ value: "RI", key: "RI", text: "Rhode Island" },
	{ value: "SC", key: "SC", text: "South Carolina" },
	{ value: "SD", key: "SD", text: "South Dakota" },
	{ value: "TN", key: "TN", text: "Tennessee" },
	{ value: "TX", key: "TX", text: "Texas" },
	{ value: "UT", key: "UT", text: "Utah" },
	{ value: "VA", key: "VA", text: "Virginia" },
	{ value: "VI", key: "VI", text: "Virgin Islands" },
	{ value: "VT", key: "VT", text: "Vermont" },
	{ value: "WA", key: "WA", text: "Washington" },
	{ value: "WI", key: "WI", text: "Wisconsin" },
	{ value: "WV", key: "WV", text: "West Virginia" },
	{ value: "WY", key: "WY", text: "Wyoming" }
];